### ISSUE TITLE
about processed dataset

### ISSUE THREAD

**Issue by Eddie-Hwang** [BenSaunders27/ProgressiveTransformersSLP#11]
Hi,
thank you for amazing work!
if you don't mind, can you please share your processed data?

Thank you!

**Comment by BenSaunders27** [comment]
Hi Eddie,

Unfortunately I cannot share the full data files. There is an example in ```/Data/tmp``` to base off.

Thanks,
Ben

**Comment by BenSaunders27** [comment]
Pre-processed Phoenix14T data can now be requested via email at b.saunders@surrey.ac.uk.

**Comment by hacker009-sudo** [comment]
@cripac-sjx, please share the pretrained model, if you have stored it somewhere. Request you to please help it is really really urgent.
