### ISSUE TITLE
Can you share your train.log ?

### ISSUE THREAD

**Issue by JECULAI** [BenSaunders27/ProgressiveTransformersSLP#16]
The DTW score seems to be import during training, but we do not know what a proper score should be, can you share some details about your training?

**Comment by BenSaunders27** [comment]
I have shared an example train.log file under Configs

**Comment by hacker009-sudo** [comment]
@JECULAI , please share the pretrained model, if you have stored it somewhere. Request you to please help it is really really urgent.
