### ISSUE TITLE
Could you please share your pretrained model?

### ISSUE THREAD

**Issue by hot-dog** [BenSaunders27/ProgressiveTransformersSLP#2]
First of all, appreciate for your fantastic work! I want to write a demo based on this work, could you provide your pretrained model? Thank you!~

**Comment by kapoorparul** [comment]
Also, it would be nice if you could provide DTW scores for test and dev sets.

**Comment by BenSaunders27** [comment]
I have shared a pre-trained model at https://www.dropbox.com/s/l4xmnybp7luz0l3/PreTrained_PTSLP_Model.ckpt?dl=0. Please read the README to understand how to load it.

**Comment by hacker009-sudo** [comment]
@BenSaunders27  @hot-dog , please share the pretrained model, if you have stored it somewhere. Request you to please help it is really really urgent.
