### ISSUE TITLE
151 values 

### ISSUE THREAD

**Issue by Tejaswini2612** [BenSaunders27/ProgressiveTransformersSLP#24]
Hello Ben,

I was looking at the 2D to 3D conversion and I am not sure how you get the 151st point, I understand for each frame we get 150 points from OpenPose, but how is the value for the 151st point deduced? Is that similar to the counter explained in the paper?

Looking forward to your reply.

Best,

**Comment by thiagomcoutinho** [comment]
Yes, the first 150 points are the skeleton, the last one is the counter.

**Comment by hacker009-sudo** [comment]
@thiagomcoutinho , please share the pretrained model, if you have stored it somewhere. Request you to please help it is really really urgent.
