### ISSUE TITLE
2D to 3D pose estimation on RWTH-Boston-104 dataset

### ISSUE THREAD

**Issue by divyachhipani** [BenSaunders27/ProgressiveTransformersSLP#26]
Hi,  

I am working on a different dataset then the one used in this implementation which  is[ RWTH-Boston-104](https://www-i6.informatik.rwth-aachen.de/aslr/database-rwth-boston-104.php). Videos are grayscale but skeletal poses from OpenPose are in RGB and so the frame image is of dimension (312, 336, 3) . This is giving me errors while using [3DposeEstimator](https://github.com/gopeith/SignLanguageProcessing/blob/master/3DposeEstimator/demo.py) suggested.  Can you please help me with any preprocessing step to prepare my frame for input to the 3DposeEstimator. I am very new to deep learning and computer vision domain and any help will be greatly appreciated. Looking forward to your reply.

Thanks,
Divya C

**Comment by hacker009-sudo** [comment]
@divyachhipani , please share the pretrained model, if you have stored it somewhere. Request you to please help it is really really urgent.
