### ISSUE TITLE
SLP for text to Pose

### ISSUE THREAD

**Issue by divyachhipani** [BenSaunders27/ProgressiveTransformersSLP#29]
Hi,

I wanted to generate SLP skeletal sequences from sentences. I changed config file Base.yaml for src = "text". 
It trains alright but the videos generated during validation are of duration 0 secs not even plotting the ground truth. 
Please guide me as to where I am going wrong.

Thanks,
Divya

**Comment by FangSen9000** [comment]
You don't have to close the issue. I have the same problem in https://github.com/BenSaunders27/ProgressiveTransformersSLP/issues/28

**Comment by hacker009-sudo** [comment]
@divyachhipani @FangSen9000 , please share the pretrained model, if you have stored it somewhere. Request you to please help it is really really urgent.
